### ISSUE TITLE
Meet error when num_workers>=2

### ISSUE THREAD

**Issue by HaoerSlayer** [Lyken17/Efficient-PyTorch#13]
It seems that multiprocess can not pickle self.env because of the type"environment",is there any way to solve that?

**Comment by HaoerSlayer** [comment]
I try to move the definition of self.env to first visit of getitem function and it works well~

**Comment by Santiago810** [comment]
> I try to move the definition of self.env to first visit of first visit of getitem function function and it works well~
where is the first visit of getitem function? define self.env in getitem function?

**Comment by Santiago810** [comment]
> I try to move the definition of self.env to first visit of getitem function and it works well~

where is the first visit of getitem function? define self.env in getitem function? @MorningstarZhang
