### ISSUE TITLE
val.lmdb制作与调用

### ISSUE THREAD

**Issue by carol007** [Lyken17/Efficient-PyTorch#14]
`python main.py  /home/likunyan/Imagenet --lmdb `
会因为找不到val.lmdb报错。但是val的目录下只有文件，没有子目录，与train结构不一致，该怎么处理这个问题

**Comment by Lyken17** [comment]
Use the following scripts

https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
