### ISSUE TITLE
GIL Claim 

### ISSUE THREAD

**Issue by harveyslash** [Lyken17/Efficient-PyTorch#19]
I am a bit confused about what you mentioned about the GIL not allowing truly parallelizable code. The official docs [here](https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading) seem to claim if you set num_workers to anything > 1, you can use individual python processes.

**Comment by Lyken17** [comment]
GIL is about NN.DataParallel

**Comment by harveyslash** [comment]
I see. 
Thanks for clarifying!
