### ISSUE TITLE
About the msgpack 

### ISSUE THREAD

**Issue by Solacex** [Lyken17/Efficient-PyTorch#7]
I noticed that you are using pyarrow for serialization and msgpack for deserialization, Do msgpack have faster speed in deserialization? 
I have some problem on the msgpack when using:
![image](https://user-images.githubusercontent.com/12868455/53297627-01cefd80-385c-11e9-9f84-b1a7574e2b3b.png)
the error is:
![image](https://user-images.githubusercontent.com/12868455/53297625-ebc13d00-385b-11e9-9062-7c533d484a2e.png)
while I using pa.serialize wirh no errors?
Have you met this problem?  or do you have any advices?
I think it may caused by the version of msgpack, so could you provide with the version of msgpack?

**Comment by Lyken17** [comment]
I am using the latest version of msgpack, not sure why you meet the problem. 

The settings are adapted from Tensorpack. In fact, LMDB does not specify the tools for serialization and deserialization. You are free to choose whatever you want (as long as they are compatible).

**Comment by Solacex** [comment]
What's your python version? 2 or 3?

**Comment by Lyken17** [comment]
3.6

**Comment by Solacex** [comment]
Hello，
based on a small example, msgpack indeed has a much faster deserialization speed:
![image](https://user-images.githubusercontent.com/12868455/53315291-68582800-38fd-11e9-9698-aad5f6262b98.png)
